name: Générer un APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    name: Build APK Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      - name: Compiler l'APK avec Docker
        run: |
          docker run --rm \
            -v "${{ github.workspace }}":/home/user/hostcwd \
            kivy/buildozer android debug

      - name: Uploader l'APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-debug
          path: bin/*.apk
          if-no-files-found: error
          retention-days: 30