name: Générer un APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    name: Build APK Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      - name: Compiler avec Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1.1.3 # Utilisation de la version v1.1.3
        id: buildozer
        with:
          command: buildozer -v android debug
          workdir: .

      - name: Uploader l'APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-debug
          path: ${{ steps.buildozer.outputs.filename }}
          if-no-files-found: error
          retention-days: 30